
package com.jamasoftware.examples.soap.wsdl;

import javax.xml.ws.WebFault;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.7-b01
 * Generated source version: 2.2
 */
@WebFault(name = "WsException", targetNamespace = "http://v3.ws.contour.jamasoftware.com/")
public class WsException_Exception
        extends Exception {

    /**
     * Java type that goes as soapenv:Fault detail element.
     */
    private WsException faultInfo;

    /**
     * @param message
     * @param faultInfo
     */
    public WsException_Exception(String message, WsException faultInfo) {
        super(message);
        this.faultInfo = faultInfo;
    }

    /**
     * @param message
     * @param faultInfo
     * @param cause
     */
    public WsException_Exception(String message, WsException faultInfo, Throwable cause) {
        super(message, cause);
        this.faultInfo = faultInfo;
    }

    /**
     * @return returns fault bean: com.jamasoftware.examples.soap.wsdl.WsException
     */
    public WsException getFaultInfo() {
        return faultInfo;
    }

}
